export const UPDATE_LOAN_AMOUNT = 'UPDATE_LOAN_AMOUNT';
export const UPDATE_LOAN_TERM = 'UPDATE_LOAN_TERM';
export const UPDATE_LOAN_RATE = 'UPDATE_LOAN_RATE';
export const CALCULATE_RESULT = 'CALCULATE_RESULT';
export const SHOW_RESULT = 'SHOW_RESULT';
export const HIDE_RESULT = 'HIDE_RESULT';
export const RESET_RESULT = 'RESET_RESULT';
export const RESET_SOURCE = 'RESET_SOURCE';
